apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-operator/
  - ../../../secrets/dev/storage
  - minio/
  - postgres-cluster.yaml
  - valkey/
  - smoke-database.yaml
