apiVersion: ENC[AES256_GCM,data:oUY=,iv:8Q/wFcr0E4CImfwh6vSa4adCPYz/QkFAQ/uKjj26fYc=,tag:NFOgPf3ecJsB9EM//R1rWg==,type:str]
data:
    default: ENC[AES256_GCM,data:xfQKSilD9yBbrE5X2+OrTSmOi0SsblJaJThqLSfJeuvJAjHJ1HaY8Dqfqt8=,iv:FSK3Udrc02n6sSqQzj3sxUVzl33NwDcs7/efJ3sSujU=,tag:uHaRNfjaUG2986bj6A7CpQ==,type:str]
    smoke: ENC[AES256_GCM,data:ioaGOU61oSEdYKk+8wNHIvVLteMLE+c/xqqpswyBLkCqx0pNTuaCEYQIq4I=,iv:eObeqF2F+U4XYifp2g4Ez6hRX+Lnc+D77UW4pdIHmkk=,tag:K3hY2YjBsjr0iIvYKPy+cw==,type:str]
kind: ENC[AES256_GCM,data:XH1Rjcq6,iv:wdNLptzbkrJQOy8IXJ+AKmQKVq/7EW/PiWdu1/6MyIw=,tag:Ynr18mDJRKW8a/e2+MPzBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dsJr9EhnEQW/yjqW,iv:dmKZ/gQr/ugjtXvfO1RDeihXNO6iQleY0zdjsOHwH2c=,tag:8N89uLYQR2s6L2oZ4ynzpw==,type:str]
    namespace: ENC[AES256_GCM,data:RMHN9NKvdg==,iv:SlnSJujPxV1IyNuoaBEExSvxhIQsA/paqVnfPCO6MXE=,tag:fZsB+Pj9I+QH9DNcp1Vmjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNlFLWC84TG1lV216R2t0
            Tm5TNE4vYmJwYzVNc3pmREVabjUvZGJkdFJzClZwRW4raWFuVDJ5dnhzS3dnN2J5
            UkxnUGpJYlJ4alM0aEJJOVIxUUVBZ28KLS0tIGk0ZVJ4TXp0Y3pCNzdqRitkWkJ3
            WHNHTHYxZnlOL0hHOUtTdUJPQldRdHMK8Pd4FI2EHEFyshGJX82F6F26zqta79rN
            E5JmSINw49HWs5noEHHGabHdbyl+v1lq73dm4o0XPSKlhMiGMVOhPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-08T17:43:49Z"
    mac: ENC[AES256_GCM,data:Ts1knrISlpfkP6dXkTnMCB8enbMEDEMmf1ROZN984dZ7gmrirEOA9q1vX3s+nnK5CFw4edlDZrbXT/XFx/wv2qfKDGmZOoieacqpmwnRmyTUDi6Yl8PfdRDjWDe7gn1KPYLbFXatUzymjEnpDaQtFOmg63EQR9ZEGV1XPiCfr4E=,iv:WxUt8fUOBwiyaaQ7cz8ga3Q0pCjOnq5azIApzUQw3j0=,tag:5sy4YvXGyVEDkL+yCi87Qg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
