apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak
  namespace: storage
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: postgres
