apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator/
  - ../../../../secrets/dev/platform/keycloak
  - keycloak-database.yaml
  - keycloak.yaml
  - keycloak-realm.yaml
  - keycloak-httproute.yaml
