apiVersion: ENC[AES256_GCM,data:meU=,iv:64Xt7EewrEhKY/+9TQYxDe8i1OdyXruhrZ5QhUfwxMc=,tag:N8iSf6rz5fdhXGa/gfO7JA==,type:str]
kind: ENC[AES256_GCM,data:R1ylfTYu,iv:Vaayi0iEz8Ukie7OV5LH+71narvVjsP0TE+gA7ZuyNg=,tag:y9SDYgNDU6qQral6y/8s5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ui2jXVapbQECiBhi,iv:DBAvkIvAjC9fajtD8ERpRiPxCKiso23HlrpI7pHP7n8=,tag:Z5suCwjtms+FJy4TAi+OdQ==,type:str]
    namespace: ENC[AES256_GCM,data:zsvcNNWVpA==,iv:NTWrV4gv/kxiX6kXelAKNsynB7om8KGSHt3xLp7zQeY=,tag:iEI7nhixQgue/03qT+MICQ==,type:str]
type: ENC[AES256_GCM,data:Dqo+cJY7,iv:MbjPKfdLFcUqtLrkaIwvrTjZCnqwJHodtkZYNV0LgjM=,tag:K01d5GC+b6laaNjcs1/KhQ==,type:str]
data:
    accessKeyId: ENC[AES256_GCM,data:Qq5QQLsZSvMMe4FlMHQPK93wkNiBVtVHr+uU3Q==,iv:yOG5/HYhJ2/Gpbgbfk3pY3/Gv/MTHTCQmP+Rte+Buuw=,tag:D7FoTLyoYapnBWKkRf1mLA==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:vF3KGsReUgFX15zupPiq2hakuZY2ICwT2e4Tu6T7SIBkdUaViUgqkDrtmumuJcG9lPf7D0z4AsA=,iv:fFHeJI9A/AqyjpALnFZLXUS3o73ZFYh+AuQjznpBV8Y=,tag:4/6JV51uDklyL+gF8bMU2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMnFsTFBUVGNpUlp4WlNN
            NWwyTEdtYkVFdTF4Q05QUUpsRE45b3B5dmtjCjlaUEpPdDdxUnIxejVXakJCMjk1
            WHRhMTVpMHRxcC9uQ3hMWGtleGJSR1kKLS0tICtobFlBWWpIN0lLN0dzZXdkUC8r
            NVlKdVVyeXluNDR0eFRnRE5QdzdHWHcKU4OERnQDuH3W/f0JH7GGPVxw8VBGdpsB
            jPoEuIkw4M7+UPk3Bc8MfuGXMmh482ajt5Bfr171Wy4hYc9PCQ3eVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-11T17:15:43Z"
    mac: ENC[AES256_GCM,data:7ZIfty4hvM2/tpCINbkywxyAN/jmCt+L+DQihWTQaHrhiE6UvnBt/9HSRe21EXic9kNuq/BOaxL9MsYvOc1v43OSz/SwtidDrdqsu2vZRYQvRMwiynUwMqZPEnkEHD1IUL/h7TP3MyIfAwuEpcmd4KZ2+w6hYoGzItAl7IYhKs8=,iv:T6WaLuS5OUKhSKHhD6/ErOPHLNC0J0DxHAOC0CeqYeI=,tag:TVbNkUifhc6Yx/QN3b0XUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
