apiVersion: ENC[AES256_GCM,data:A4Y=,iv:w4n0F9yn4FFTT7IesXUO/rfV520chJ9v4LiQnOP4ScE=,tag:vAJIoB1Xwk3h1OUTP02n9Q==,type:str]
data:
    password: ENC[AES256_GCM,data:QaqptCuVz/mgfbKeAJAQaZ10zL6ECzJYHCBF8pc06XOc6F8GlS7za/pFcYY=,iv:3YNdOeVIZHHLSq45t2R3Tco5Exm7ADiYqa7Yt4TB5Qw=,tag:1AiOSfNlLnu1o7EpWp3JwA==,type:str]
    username: ENC[AES256_GCM,data:E0xCh/eswxXAPreFBzcXPhfHpx8=,iv:lElwzOfceYnmkfExaDn/WN2g/7kEQ78nNT1OY22Ig/o=,tag:XnoAYjUpzsuh+UG9doO0MQ==,type:str]
kind: ENC[AES256_GCM,data:EbYHUY0S,iv:1Vs12YopI5b6RIUYkIy77qw4uzfEy9N/9hVB74yIyvs=,tag:8CdRENwfEV9m/5bwDssXgg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:P9AdDgfWCIS3SByNwg==,iv:gzUtVsPoP37vcP86PU7/WVuNVafK3fM2Kzuy5aun8uQ=,tag:lCKMiN1aCyfbT3yBQMJ4WA==,type:str]
    namespace: ENC[AES256_GCM,data:jd1xGAPkoA==,iv:IKAGO0vivbe3bH57wkZc1G8CVKObP7ZPICh7aF9nBU0=,tag:l3ilqrQRWydR9Q1dU6twOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMVc3cG85RGQxaTgycmZ4
            Y0tjNzhROXRWU2tZNmFKRTRYU3VmNTQxWFdZCmdNM3VpTWtBNEFqSk1PU3luSjNV
            RUFCRXM1blluUks1TGZkb09PMnlSWjQKLS0tIC8wcXhrTkRCUFpYNm8yTWF3YXJC
            d0J0WThFbkxvbG9vZUY1VHNHbGJxbXMK/H6Z3/Y6k5bAidUJKFhvAmgfoJGOUGy7
            YEXuqocEAEE4UQldo+sBeoG/1DH8zpkjmi5jYCh4KbdhqlDUMp5mHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-09T13:18:52Z"
    mac: ENC[AES256_GCM,data:8ZYNlM+Bjpmpu1aX73LvDDHEgZL6kHj+8cy3et/ijfd/bBcu7av10qZRtZ4ANGbUFADorvWcX55rLyruN2uOBxXK+UYsEgA9fyvfuHpx3de9aqIj1lws7psbbr2LMMnmRJ+Rx5zqh4yZ7qVvFOWPwmMAusLwkwLzQXym+1QTI34=,iv:+51wTSTxkNbIdTE+JTDdyr3eY7GJvwPFnuOxHNZYBec=,tag:QyCMYQJnB12KQudFnl2lNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
