apiVersion: ENC[AES256_GCM,data:4fY=,iv:Q4SMmWhnc4+7OSyEgPwHsR8n4MsUpVbc+uUamssxaQQ=,tag:h2gJFSkY/bc0z5cwTADyvg==,type:str]
data:
    password: ENC[AES256_GCM,data:l6rui7ZQH+DGc4nqi6IIWiOTPq1tXn4vRc/ut4GsfUbzF8rzuB54rDa7lHw=,iv:XOcUlmyTMjj8QdfFE62MhK1WRH8DI9IWZj4o1XpEyZ0=,tag:zInluVfHdsXGII23kLoLig==,type:str]
    username: ENC[AES256_GCM,data:H2qmDUi9+Z0fcjyf,iv:tUgKZlR8Fd0iH45xN2ySrGuOGfEZdZOqZeaQhJgGxOY=,tag:aW+W3z2wnKon9fKiudLudQ==,type:str]
kind: ENC[AES256_GCM,data:fDFEfvQr,iv:9Rk1RCehvnw2VpTnDkhechf7Gc2RYXUmJgtrX0o4ces=,tag:96l3dFPBkSNdRV+nssCLsQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kRFjD8TpxzBipg==,iv:W5pvYWksI5StQ/Fhy2pHS+xmFFjkkgYWFnOI0yGd4e4=,tag:jity/6xLWEf0W6VH2LNlYA==,type:str]
    namespace: ENC[AES256_GCM,data:uTesn4cI1Q==,iv:5BYNzImbna+bdXoHODX8aMXv9lRhM0/pdmS4yggQmTE=,tag:+Td55nUdMpmSBcluxPVgIw==,type:str]
type: ENC[AES256_GCM,data:G1u4XyZUA79kA42A0CwCLN3CJiibo7OQ,iv:8SWZ/u/zIIFQn2IDqrT6oo3arZC2u9URvdq3/tWjhhI=,tag:YsWa7EJyiZ2p/7gnS+BPUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eVBFZDlEWldIZzV1U2xM
            M3ZtUlI1cTJCR3VyNXdKMUFEdzJqWFN4R2w0Cm9KU05hbWZJOCtUeGdieXEyUldN
            U1dURUZBN0dNYkpUbEtibVdJak9qQU0KLS0tIHRnTGV4cWV1TUtiZTF2TTZGSzJq
            L2p2d1hObG94WUdsMmZneCt3RXhtVHcKVMckouyd51dLRg19yBDrH0hYAXq1G19v
            9KnfOX+pcAN8EKUMo8q5Vvs1KHN1m9/BF2yCqe1gHjFvIqW/8e1s3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-09T13:18:45Z"
    mac: ENC[AES256_GCM,data:f8e7ZOzwya+AUHqaPA2qwgjhZLgSO2SnzIkJNGn6HQGHGKuhoilQ8fZiigsgFvvGKkXv7UtSmdwfMzMRtB6mPd+UCi6poLKwXqsktErymuIGVsgySkZiIXuxnOISjC3PLmhnd7vv4DjY+27B5jF69VIEns59KC5JDPqJCytOgtU=,iv:fVrEmOulExwYrVv9ONUzGvs6fYH/IXRfYiT13pwZAZ0=,tag:z94dLNFR/l1oGirBeuyaVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
