apiVersion: ENC[AES256_GCM,data:Mj0=,iv:LXkQ5vt2jtNTDBNAuf1/zTmafEyiZz3eoPou2PEl7Jg=,tag:OV6sm0fXmdlqSwq1ocL49g==,type:str]
data:
    password: ENC[AES256_GCM,data:39o52xo58LqCSJ9lSCba5MLUBhyl+m95yjWRiePk5AdAjGXv+WOfqwjPze8=,iv:04/mYMp0H5yag30m7FQRXhXVZMH2CtAT3Bn4Xmnc1/8=,tag:gFWQ4z0VfRtrpQaSONoWgw==,type:str]
    username: ENC[AES256_GCM,data:SvzhQkug63XjBEb2,iv:aGGEhUxTw4cl3WsLdTkQ3snst413FNRQDKqWvdT0wDM=,tag:tRB7PIA37R0F9p+OWAOKwA==,type:str]
kind: ENC[AES256_GCM,data:SR3O4CyC,iv:I9k4Ke9lAbnsMO8Xlqk5+GItS720Yh2Facq6nPtsAtA=,tag:Mf8eowz+jHjb05PhXtxKog==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UTMFxmf8QxM9yg==,iv:QkkBRw5GsQ3uEh/UV+aB9ACzk5HXggX4eJ0A6CCeCX0=,tag:WyGzkD15EUcd5aMJZbriTw==,type:str]
    namespace: ENC[AES256_GCM,data:5AC2qMIpJw==,iv:UQlYeY0eDwpJkkloyALv0t6QhoidUMXXvbsyU9VihAw=,tag:w6Nv9O/oKctL3RvwMYDRYg==,type:str]
type: ENC[AES256_GCM,data:KCNs9hqCMRtj9GYkGiRLE1Zpm9R5WULL,iv:eW3T5t6w0p55VVhgUFeJGrSugO3UeOSt3rX6HF0Ho+8=,tag:BhprGy1TkxAb+T15j2KJiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aitkYWVzNHVMNi91SnJ6
            UUpianpDZkI1VzlLMklwQkdOMjVoYitSMDM0Cmc0ZEljUGhGSHNzdkdFM01zaVNq
            Um05cC9BWk56WG5WT2tUMFFiT1BmUTQKLS0tICt2MXFRYkJxKzZNZlRYbEtyT0tn
            MkhjMm5PTzlLRHNad0Q1alJiRzRJWHcK1nhG7xDtKW88/EgPvDpcj9EBmW64BcRn
            v2+tteDPmOPGVccMvijjSkz8kLZNu5OpGJLMeo+gLSFKk/59wGrbmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-09T13:18:45Z"
    mac: ENC[AES256_GCM,data:GemIkKfdhk1duIkulyr4NGudlGjqSFwNwTe9LNjyOnKqtAna7Ut+AYUxAvzo0qd8nZMOnWuB9pTkZpTHlyQZ6jEz/dpQms4MBghoZ7s2HziiAA4fJUDVhSvLEhoBXCs464bCoPrNF/c0NtAv3NVgvI6n6pUm0akUoena6Mf2Suc=,iv:tSuKmYDpfT0hFz5naPaLSwA/9fLKPbICMzx+ppzpmeE=,tag:KLz24ppJt5gGjLskqedFOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
