apiVersion: ENC[AES256_GCM,data:XTw=,iv:Th1wuuLiYOIiF+6HJ6p8k4Wwswb4KtQ9YZiFNxJVdLI=,tag:XGbffWLlr4TSeKrpiBY5ag==,type:str]
data:
    password: ENC[AES256_GCM,data:1okj3mrRafezzbk9CEC8nC5RcN5CUWYypxs3bAzBwmtIbFFn/gEikImmyeQ=,iv:nOPq5c+2JKfnrlRWp9CCVfO0A8HUH98HH0OV9M3gYxE=,tag:lk3IyTF4WXMUrU3NI0mDGg==,type:str]
    username: ENC[AES256_GCM,data:w+FnBwfHr3w=,iv:HBtw3PiSkhgAhktLJ2UCPlyDBeBEOCibvlSgo8Qx0d8=,tag:zE/MN2cgnNsSX4BdROpOtA==,type:str]
kind: ENC[AES256_GCM,data:FfJitRqE,iv:nloVJoeaihKnw2btaA0o6sr3vX1P0vtU4zMja1xyE0U=,tag:NzN+x0uM266MmoaU8ikzIA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w5DYtajbscZIXPZl6Gs=,iv:Kh95207TEFA1xqOEhLvefxwJzZGKRJKRourCo4+NR74=,tag:rhU3TDLevMxBJ/r2svb7DQ==,type:str]
    namespace: ENC[AES256_GCM,data:qrELL1BrvU0=,iv:DpIMXQ5R3A/yCwNXn1VcSq7ObDVaYJNsu9Aopqpw8Ro=,tag:TEWfGFyaQzutMyeQbrfWYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNzFZa0pXYXZwU0R2emRQ
            Vzkya2JjVUd5dHJUY1pUNkh2bVhxTkJ6TjBVCmwvSUdiNjhLSVRvbmRzTG94cCtB
            MEVCamZlSGRlNHBhQnI5SkltcUFkU2MKLS0tIGVPSzVIZ0NmcHlUejJYNEsyVEcx
            ay9McDJibWw3SjM0bFAxVXdKY0VESzAKSCURsjq+nJqhDmqAqKbRspJbQ9HaUXiN
            Ge/Gq36rqH5bfB/955IjqMZ6QPN9WWiwRRVB2DqYV1awWy0RbXNJCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-09T12:34:11Z"
    mac: ENC[AES256_GCM,data:iyiYZRh8CO/SVT557EnWK1V3GhudsWHNCSO431Dk8qBGR9KiJXnN8mLOEV8a/xMxDglgd6x/0tmfJdpCqkgeg+CeqQoV8LXO9hMQ5r0mnAPr1INiEJ5ogAxE8T+8s1U8scTT3Z8vs6yYCLT4eltTMfs57ccaSXo1FEk3WNyvac8=,iv:nQ16Q2V/8DD2WiObZoCc+s2VNIp0RctklAJWUdtGP9Q=,tag:ewYrVlGB8OWCjRXqikyQEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
