apiVersion: ENC[AES256_GCM,data:Lz8=,iv:dwjAObNppH0aBN3gTFWYlm6PPOR1TXu3xhoVM2FGb1c=,tag:0M8nkdhLsmm9j57wYY+ImQ==,type:str]
data:
    password: ENC[AES256_GCM,data:OR3LpSCjFto+b8DDBYNfcwqgHWC8t4atvlac7OZnCYxlARsP4Op/l8ILS1U=,iv:kmjVml2xn/bxfcHi8tb3AlsiKncg5MGpujA777rLFz4=,tag:Rqy7OVxiKnlyF63XP8dq1w==,type:str]
    username: ENC[AES256_GCM,data:tNTY80DaJpNFfQaZ,iv:rl62lTJQz9xzon3Rp0J5B0OtJkqoN1Nk83S7RRirKDI=,tag:EA6XDnq90as6vJNjYdEdug==,type:str]
kind: ENC[AES256_GCM,data:g1cEIEAl,iv:nIPd/e54dKzzbLdFsUfA5EjhhDI/Y5brXhS+Mq+Vom4=,tag:ze3zFGmqYFGUKaKnYPj64A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1hDaa8Z3V72hwpQ=,iv:SD3usztavASUhJ64crQDl0zVLqzHHL8/fErzIJoOqX8=,tag:Mgvuo8gXh4HXN3XZGsDcvA==,type:str]
    namespace: ENC[AES256_GCM,data:6LaAgFuXFv0=,iv:5nxOGHP+zV9L9qZOM5ddIhuSlSgbBzjBLZ6w97ifpFE=,tag:RcDb/cYVqc1Fip3RE3YWQA==,type:str]
type: ENC[AES256_GCM,data:ixiPEZtii2jCU/9HwA/pmvi3ZhD8NEc8,iv:lhVAkEs09AdhXw8R9iXZ9eLEf0mhfV8+clam4LL0Mfo=,tag:KZ2xJXXU9ITq/sgF+eRVWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdnNTMUZWMHNjcnJMNVFi
            RUk1UEthSVE3c0ZlN0s3cnNmSW1xWHhWcUZRClJaUHJxNXZnM3UweDFKUGdYaHBv
            YnhJMk5HdGZsSDlHU0J6T0NoNnVCaXMKLS0tIDJsRloxVnNSV0lJR3dQL2xvUUlk
            eVpTdzZ3NCs1Z0VrRjdXcDRSRTdDME0K1/CBM08Txfd+SCHUFEvDSsIkeLPjKcXU
            GfbGpofnqDClhazLkKZM81oPa6NrTrwWNYnjhp1xAmBi+kv3OUxyxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-09T12:34:04Z"
    mac: ENC[AES256_GCM,data:SaC7adv2+3FQ/QBt+0uhpw8u7Uwcf+HbMKMy9r1QrJLtqF10BeGFd8O62irACRV/Gu+SybluBwTUwfKaUvEOmL/uMIl7RWDW/LMmnm1tU//6es7jfbdTPacPBup0NYOSXv5fqSO/nhiWX1s31vMZ5ip6lHqvoEYIhI1hiNhyvb4=,iv:X6NQ3TWXGI3WXKm9tBfSpx0S9ajrpRD5D3seTAyaqGM=,tag:uh9k6uL6pf48oE892HyvRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
