apiVersion: ENC[AES256_GCM,data:jT0=,iv:J9iXlY7gd0acz05J441MaWxUGBq+rjiskaVjkealNZs=,tag:BtoEbBrVZRhaS8mNuuibuA==,type:str]
data:
    password: ENC[AES256_GCM,data:QN8QI1+6KKY5DL9Obc5jJcLIoXZvUHjjn/Wk/s7S6P5xO7c999zVKqjpNdA=,iv:wPp6FQkelqfMJfs8Is9NRjvsneAr5QtQqLKQpzyMu9w=,tag:xVTlcubuFQouVNoWAQWVLQ==,type:str]
    username: ENC[AES256_GCM,data:nOai6rYCnYDC9Q+P,iv:nozg1+KIPNo3F9olWjfBwfRwO0osSGLOJeaeuErKLOc=,tag:GoBBjGgzbqYYz0kZXd7bKQ==,type:str]
kind: ENC[AES256_GCM,data:SvbZGATF,iv:bQNlnfq05O2Xu4jQRe49voBh8uhkfgGxVIsExSTltFE=,tag:JXr5iDcxsJEA8a8IKb1nXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZdhKD9WeDQKoHD3b,iv:Ox5iM7m5VBxXAoSkA+DPDXFMkblxPfCgJAeCka28Qhc=,tag:JA8cjxFbo46WmS0KRhWTew==,type:str]
    namespace: ENC[AES256_GCM,data:FYVWSa9T8A==,iv:hDcatpK4aGkKyvT6eOvdyE541HIM8wrZ4qvHtw4hv4Y=,tag:17iuO1D1DJY+CbklFx+xmA==,type:str]
type: ENC[AES256_GCM,data:ZsjoKBmNXQgK0htkV0MYqKYj93OvB2qC,iv:kxV6nEoy8o+VDLxIeAgrtwGEbVOi/5nC5m+2+chTTdo=,tag:yFt8aGq3dJJrI6+8sksk5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Yy9tZitJOGhRSFd0QW9y
            VVM0TFI3bXBMemE1RmM5QTVYcU9iTFEvNmdRCnRyK0plYjBIdUorSW1MTitqb0p3
            cHNxWXRZWFFuK0VyR0ZrZEFFcVpHeDAKLS0tIHVtTkZjdi9nNU5PRDZLbkhEUmo5
            WmNobTJFWUR3b1ZKT1ppTDNaaTJrOEEK1e4I6Ben+cyvPa7agnWXC/IY8o2XeQlJ
            Bh9r6v/KI1oPL8uKeO1aw88PtsnOsmWqeUvI5n2U/Ib0gq0hf3r9+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-09T13:51:06Z"
    mac: ENC[AES256_GCM,data:ODXIp83yH/JtvVEccbPvM4T4KeCCd9PcVoO5s3gku39rwNCdJGE1NtKJ69T2ZfnzvZ9ufMz5a5GGfbEcKtkH1c20vXgqkkBw6FYGUqfdJyuiB4YiCvBY4OGVmvpx1BblTXLbLC5bIy7gu/wT+nR+1LJCdatCuX0o8o+pYXiUVyo=,iv:CF5CEE0VzZOIW+8qiFe3rygGqQTrtmfN96klQTQCNYs=,tag:2SSLrr2pGl28qpFAZgEOBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
