apiVersion: ENC[AES256_GCM,data:D7w=,iv:idcBZLvyNXgp9zUnDmx/Y1yNvjPJoB/mvRfFpvpQcHw=,tag:VcMBlLupLx+Unq8bAywMEQ==,type:str]
data:
    password: ENC[AES256_GCM,data:SvnShq50z6O5nB8q4+oR9ASgUxrh5/L8JW+MEr4171Iz1op3NYijJ54RhOU=,iv:sALNFJEsGaJvrS9GONpQgK09WYKk9z36GIdvo5siTd4=,tag:9jWzzwX4pqVp0MAcocbvSA==,type:str]
    username: ENC[AES256_GCM,data:yUJX48WE5tlD35Ku,iv:spyW+wjNux+pqrWiBkbP4QsC/7OxfMjPeceIaySn4RU=,tag:exED48hauLWYmOkne/CFMw==,type:str]
kind: ENC[AES256_GCM,data:R+FRXP+y,iv:7Hfm4DJucnhywNLoSVSci9SzGydVDU8k2E2lXJ+gGI0=,tag:dmgFvBYcBlcnN4ZjNWNbhw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oYWtGEERBtSxzps=,iv:T9bGKCRAk1rPMM/grBBGXtf7sSaWgpTDJz3+K+jO220=,tag:DwlymZhIuCbva73d1bWoQw==,type:str]
    namespace: ENC[AES256_GCM,data:BRuX7WWj2Q==,iv:7YIZZOJeeWmbAvSSBzaL/bOvWUDOf/eJ0gUF8TC8ncs=,tag:B8QZ+fRFFy2gC/p+Az5X6A==,type:str]
type: ENC[AES256_GCM,data:YzKqfJjMAvFihhRwqVRv1wbfVhKI+iKk,iv:Z/VRzyWTUiIYXajdHBpzRHGc/DEK7z+1zWt9fVSZZfw=,tag:diKak/b1v+FR6+3iWRuA9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNndDeXdvMjBRbjJELzBm
            RlFveUpOZjRzaTRyY2J5T1N1YlNpUEgwYUVrCjMzbytxWkZBWTJMNUFkL3NJWDZ1
            N21XWnp1dGd0elZTK3FZOHE4YzVjTWcKLS0tIE52SmJiQjRpdnJjaEczajRLTHQ3
            SUpETEJ2VHpBR3RQc3NickhySEhZVFUK3Fgufd/zEVQXgn4XySzUIQ/MmEToZmDp
            S0wTcqghuFbrdEoqf+NgvYs4nSPhDJ935oiBP7+4oGn3MBbi1iY/LA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-09T12:34:04Z"
    mac: ENC[AES256_GCM,data:P8d9poV0D6CtFkzn1rvfM4NQUFxmWxfNyRQa+ISaSLUnLe2unjATb5Xjxkk0zZ4POd6gtkGjYXJfXunsLb1HrAxEhKXSUNL5h1jcuObT5tPDYB0QO1AobJj+JswfvQsQU/dYf6SQPD/CI6rnqq4Oxy2XuuIhoNpDNcJ9LcoA9mc=,iv:p+iHu18II5IdcK+m7m2KZqHtd4gWtOejyTZ/C+qspsE=,tag:fksE/7EZDlsPDRj7GHYxHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
