apiVersion: ENC[AES256_GCM,data:76g=,iv:S+zVZa6rZweghXqaZwBKKbWUdFC+VgGXvoqDjxYFJMw=,tag:qAi9cMzfUSN4dUc37LzZyQ==,type:str]
data:
    password: ENC[AES256_GCM,data:s7IEfqN2pdYMAlOOAp6WUO8stO6piK2aUNk5Z449ufTnZgH8HSgmjTHqvhg=,iv:HqGt/Shr3jBfATvu4RhpzqrKmZAwlnks9LikD55UKvY=,tag:rXAlmPCWnPCWEF9RBwdmIA==,type:str]
    username: ENC[AES256_GCM,data:OTNNTyXq5KM=,iv:vDNBP5UHUNHt9fVE499/t3+Pj8CcTdLKJ0LQW0XTGJU=,tag:n2t4buZdQsFvjJFN+ZscRQ==,type:str]
kind: ENC[AES256_GCM,data:fzhNoDVa,iv:5SKVvyTCetenabya8takUy7Qi544QFPGL1LSwZMhFP4=,tag:FA9U2KpwMi6tnjv0nwWQ8Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JfmPZbILPbg=,iv:8oDkI+YdWz0JvGl8LEsQCQkhRCP3m6hK/fFpzwjWWBI=,tag:INnKrInOnHAUBkrPuAIung==,type:str]
    namespace: ENC[AES256_GCM,data:udtK0gw+Bw==,iv:SoyvPqHVsKKDcXQWkea9d1d/RsnSq3lMSIM2yGR3WeQ=,tag:8A1dSid/RGjSRpXOQLzN2g==,type:str]
type: ENC[AES256_GCM,data:AlBEblSOnG/OQIlVJ7MyD/1b4KSvzF9x,iv:6wD5QuBMyh96bkxsfewlZqxDkMfQOnC/oQvTsidRQuk=,tag:iGKzbkr2X3xMDr/H6BCN5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSk1SajNHdGxxM1B3UUFa
            TGhvczdnRStBTzh4R0FKZ1B1UG9hdm91N2hjClBYZGFndVd5SkpDR3NjMFNrb0di
            elZuUDEvS2d5djhVT0JNTytGN2NOeTAKLS0tIDdBK2ltYllnK3Z2bTdTdjQzNVd3
            RnJFY2xxZTRhMlMxU25TZ2Q3eWJhQWcKKfkXGyxKLZvPqMHjpT57Qt9Wy48zB673
            Bz+OCLJxfCVSZ4peHdDuLzhR3e5ttOV/4U3ZkLDa/8kGXZnd/UumIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-08T17:43:42Z"
    mac: ENC[AES256_GCM,data:gvNr1F2V9wNFK9TRfP+5wWNbU04xim4J1yWfq1M8AdGVczmCQp6y/N1n9Pa8hFhp9I5OYfhnaC9aM3RbXiHblnyVtFM4sWgxq7i3g2zwS4ABJHx9vXL77qwudYglvwv+GVI402XC0TgG2wRqpsWkb1FfQdSm59ipZVWQojrWMrw=,iv:Q9CzNyWjOChB/c4BM71c5Q+UhcowIl7U5HFu1PMN1iM=,tag:t2m6U64eR1raNs2iY/+4xw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
