apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flagsmith
  namespace: flagsmith
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  parentRefs:
    - name: agrippa-gateway
      namespace: istio-ingress
      sectionName: https
  hostnames:
    - flagsmith.127.0.0.1.nip.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /health
      backendRefs:
        - name: flagsmith-api
          port: 8000
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: flagsmith-frontend
          port: 8080
