# Workloads serves davidsouther.com, trips.davidsouther.com; and eventually
# ailly.dev, /agathon, /blog, and DavidBot
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec: {}
