apiVersion: ENC[AES256_GCM,data:1P8=,iv:toOfZHhxd4x1L2Puslo2qXUbUFc4oyHImO4YjXTRaq0=,tag:wG/RA7iMX1eIKWmFb7iHUQ==,type:str]
data:
    DATABASE_URL: ENC[AES256_GCM,data:t/+u+JhVByey7Syz7oKzSCOb53YK6JtL1Yjny9cR78HtnrHBY+dos1Mv3qZlX1Tl56ZY/SO96yQ7blNTui5U7/589D7wlV8wu64Ddmtjs+YWmbz64atTwVE/8JoEdBUJQ4OYcLWVmhr/SW0fWGiKhWZ1O8VN76OKhG75xw==,iv:t7KENmGWkLEpWpzBNDTqOuoaN4DgFCGPNtx0R8tZ2+I=,tag:VzwMfhSaSXxruFLxKeg5aA==,type:str]
kind: ENC[AES256_GCM,data:B9d4ZMAQ,iv:pHMLO+eAGgRAiN49V5C8qBHgJDLgDhxk95cKbBTGWL4=,tag:iB+lfgQpacMXN7AgKybwhA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xR7KgKzCmHkr9HN9t8ZfhMpOTcpLEw==,iv:xE3KK2VzDA6SQfF7a6qwtWEAkMldde6UJ9LcNMwBrRU=,tag:xDePPVFiJIY7ZD6ocJie/Q==,type:str]
    namespace: ENC[AES256_GCM,data:i3v1uc7FO7et,iv:9qra8LHM6ghXJSVOy8JfJmQbeoYfMuRp+aVUqQewRFE=,tag:55d7gzItqzub9BaZPywV6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYnBDL3pVTnZzM0tzejRy
            eGlyTnkzbkZhM0xOdHNGUFd2T0NpZyt6T3p3CjRXMWNQM0piL0poT3VNQ0FNZ0h0
            NitPL1k0NFpHdTBNRCtaODRNR2FoTGsKLS0tIG5YU012SER1MzJnaWxBeUFYSjJ0
            SmoyUlpHNzFyNTJOT2xXcmFBOXBVYzAKeNNCezLyyBWoQPX9jbtgJeeAzrDNwuKJ
            a+iXEnfvhJxbQc07MLPAC1qZxgJbSuBVpNsenJQo2EzD6ofB5gCGWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-09T13:51:06Z"
    mac: ENC[AES256_GCM,data:cxYrQntjOvgH6C258d//xm9bloSk/ivhsZQp5uQwc9/iBHfz/DQLtnOlVt+XY4rTHOayjje2tPlE8RXI/9ch8vPoX9k6oe4803C4j/dO+UYshtnRbAcZC/umCraDrasRGW5snUFYTXFsMRUeefkbIhsDAfofHk2/Yv0r3eV2R40=,iv:X8fKOVsIeCIARa+k0Kyqrw42SQxUnHMD/R4oEiaGPCs=,tag:A8c9NYn/iVCNsKyvJpye1w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
