apiVersion: ENC[AES256_GCM,data:iRc=,iv:mUjWX3Sheuydb6VJYqfHsxRApe3gRxY26CFJMvk05o8=,tag:lHu5bXRgkkK3OBTRvfXflg==,type:str]
data:
    SECRET_KEY: ENC[AES256_GCM,data:/oeWkOLygZqT2pSrhRlNxq+03US5cYN4jVoFRowlmcPHIVK9mqfPFsGQn1Xdjg87gyWjextS9VV0JR626gkQZRqylCh0xy+0wDX8rfYT+9dG+PYveDpBcA==,iv:6rY8UZElBfLCJmClaJlJxFaD8NlP0nBJg2LuSiOfSpg=,tag:SF5NSBIEjUPAmSpQTJ1DOg==,type:str]
kind: ENC[AES256_GCM,data:AH1SPhTE,iv:8eGWFYV7h0LxBqlJogn51a99iz4Sccq9Uc4Xt+d7GAE=,tag:aZmCBxbXN+QNxwWkEWHt9w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UgbQ0GHcQzrl7S4J06TKIQywjcA=,iv:f1e/i60goR/rGFOag1ZzFN+8qX/zvmqb0fVX/kmYNRU=,tag:ushssUuRyZvWuD7YSaSU7A==,type:str]
    namespace: ENC[AES256_GCM,data:EU39wybhFSjS,iv:uu7a55ZguU3haicPvhTx3slrwBqE3tm4ap6Ao+lAj/Q=,tag:zp2FUGy5FpjuRB1xTo3u3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN0t0NkhGbGsvazBkb01r
            dmJFclVzL2JKQlJyU0lqWHVRaTBud2RGZXlvCkRhZGowM0xmRVMzcU50WjFQR1hT
            bHh2Q1g0Q0F2L3RIQysvR2wrL0U2NzQKLS0tIFhkL0I2a1VjSFdYYmJWWG5nU1Bo
            TzdhTy8xTjJjblBVZU4zUlc0U0pJakkKPnyoRPu+2p1niRSNkpXmgz5q3QvL+gR1
            d8ZXEhZpANHBBAXck1znEtWxn9cawwOTc732CFrkK9y21qdguYoJ+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e8wr0f85w0yfqgxc3pc6426ghlu5xt069znn5yuwrtwz30u23quqjcx6vc
    lastmodified: "2026-07-09T13:51:06Z"
    mac: ENC[AES256_GCM,data:FRWLf3ObQOPxfo9xrG1u+OYpDSqZgGNB2gZ+UGQIT8TzJE1A/LPd4usb3AtFjwuKrnc96oHzi2j6LYtEidhid6orPUbuD/yXR4WRA2dHwn9vvFJA4TvEFdY/H/mGevxK2UBv3AjN118w0eWGigZBCNPZfmCkax9ybkM7j/cipZo=,iv:7EdgKFgrGNWY6CrMPGve8lqv7Q2BnVkv2PjVEgE6txY=,tag:wI6uOqG21LFkPtZVh2Z+6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
